#!/usr/bin/env python3

#display a welcome message
print("The Test Scores Program")
print()
print("Enter 3 test scores")
print("=======================")

#get scores from the user
total_score = 0
score1 = int(input("Enter test score 1:"))
score2 = int(input("Enter test score 2:"))
score3 = int(input("Enter test score 3:"))

#calculate average score
total_score = score1 + score2 + score3
average_score = round(total_score / 3)

#format and display the result
print("=====================")
print("Total Score: ", total_score,
      "\nAverage Score:", average_score)
print()
print("Bye")
